version: '3'
services:
  mongo:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: dbuser
      MONGO_INITDB_ROOT_PASSWORD: userpass
      MONGO_INITDB_DATABASE: walletdb
    ports:
      - 27017:27017
    volumes:
      - /home/fernando/Desenvolvimento/Docker/Volumes/MongoDB:/data/db
    restart: always

  mongo-express:
      image: mongo-express:latest
      ports:
        - 8081:8081
      environment:
        ME_CONFIG_MONGODB_SERVER: mongo
        ME_CONFIG_MONGODB_ADMINUSERNAME: dbuser
        ME_CONFIG_MONGODB_ADMINPASSWORD: userpass
        ME_CONFIG_MONGODB_PORT: 27017
        ME_CONFIG_BASICAUTH_USERNAME: dev
        ME_CONFIG_BASICAUTH_PASSWORD: dev
      depends_on:
        - mongo
      restart: always

#  app:
#    build: .
#    ports:
#      - "8080:8080"
#    depends_on:
#      - mongo
